# Generated by Django 4.2.16 on 2024-11-16 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_updatemodel_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view', 'Can view the books'), ('can_create', 'Can Create the new user'), ('can_edit', 'Can edit the details of the book'), ('can_delete', 'Can delete any details of the book')]},
        ),
    ]
